        subroutine template()
          use OAD_tape
          use OAD_rev
          use OAD_cp
          use revolve

          ! original arguments get inserted before version
          ! and declared here together with all local variables
          ! generated by xaifBooster

!$TEMPLATE_PRAGMA_DECLARATIONS

! external C function used in inlined code
          integer iaddr
          external iaddr


          LOGICAL :: initialized=.FALSE.
          TYPE(rvAction) :: theAction
          CHARACTER , DIMENSION(80) :: errorMsg
          integer :: cpCount
          integer :: currentIteration

          currentIteration=0
          write (*,fmt='(a)',advance='no') 'number of checkpoints = '
          read (*,*) cpCount 

          CALL rvVerbose(3)
          initialized=rvInit(n,cpCount,errorMsg)
          IF (.NOT.initialized) WRITE(*,'(A,A)') 'Error: ', errorMsg

          DO WHILE (theAction%actionFlag/=rvDone)
             theAction=rvNextAction()
             select case (theAction%actionFlag) 
             case (rvStore)
                call cp_write_open(theAction%iteration)
!$PLACEHOLDER_PRAGMA$ id=4
                call cp_close()
             case (rvRestore)
                call cp_read_open(theAction%iteration)
!$PLACEHOLDER_PRAGMA$ id=6
                currentIteration=theAction%iteration
                call cp_close()
             case (rvForward)
                our_rev_mode%plain=.TRUE.
                our_rev_mode%tape=.FALSE.
                our_rev_mode%adjoint=.FALSE.
                do while (currentIteration<theAction%iteration) 
                  call loopBody(x)
                  currentIteration=currentIteration+1
                end do
              case (rvFirstUTurn)
                our_rev_mode%plain=.FALSE.
                our_rev_mode%tape=.TRUE.
                our_rev_mode%adjoint=.FALSE.
                call loopBody(x)
                our_rev_mode%tape=.FALSE.
                our_rev_mode%adjoint=.TRUE.
                call loopBody(x)
              case (rvUTurn)
                our_rev_mode%plain=.FALSE.
                our_rev_mode%tape=.TRUE.
                our_rev_mode%adjoint=.FALSE.
                call loopBody(x)
                our_rev_mode%tape=.FALSE.
                our_rev_mode%adjoint=.TRUE.
                call loopBody(x)
              end select   
          END DO


        end subroutine template
